export const ADD_GENERAL_INFO = 'ADD_GENERAL_INFO';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const ADD_DIRECTIONS = 'ADD_DIRECTIONS';
export const TOGGLE_DIRECTIONS = 'TOGGLE_DIRECTIONS';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
